import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderComponent } from "./components/header";
/* import HeaderPage from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
}); */

export const metadata: Metadata = {
  title: "Expo SO",
  description: "Generated by Christian",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-800 text-gray-100 font-sans antialiased selection:bg-[#ff4694] selection:text-white">
        <div className="min-h-screen flex flex-col">

          {/* Fondo gradiente */}
          <div className="fixed inset-0 -z-10 bg-gradient-to-tr from-[#ff4694] to-[#776fff] opacity-20"></div>

          <HeaderComponent />

          {/* Contenido principal */}
          <main className="flex-grow py-8 px-4 sm:px-6">
            {children}
          </main>

          {/* Footer */}
         {/*  <footer className="bg-gray-800 text-white py-8">
            <div className="max-w-7xl mx-auto px-4 sm:px-6">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div>
                  <h3 className="text-lg font-bold mb-4">Sistemas de Archivos</h3>
                  <p className="text-gray-400">Información actualizada sobre almacenamiento, memoria y organización de datos.</p>
                </div>
                <div>
                  <h4 className="font-semibold mb-4">Enlaces Rápidos</h4>
                  <ul className="space-y-2">
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Inicio</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Tutoriales</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Recursos</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Contacto</a></li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold mb-4">Temas</h4>
                  <ul className="space-y-2">
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Memoria Secundaria</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Cache</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Swap</a></li>
                    <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Directorios</a></li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold mb-4">Suscríbete</h4>
                  <p className="text-gray-400 mb-3">Recibe actualizaciones sobre nuevos contenidos.</p>
                  <div className="flex">
                    <input
                      type="email"
                      placeholder="Tu correo electrónico"
                      className="px-3 py-2 rounded-l text-gray-800 w-full focus:outline-none"
                    />
                    <button className="bg-gradient-to-tr from-[#ff4694] to-[#776fff] px-4 py-2 rounded-r font-medium hover:opacity-90 transition-opacity">
                      Enviar
                    </button>
                  </div>
                </div>
              </div>
              <div className="border-t border-gray-700 mt-8 pt-6 text-center text-gray-400 text-sm">
                © {new Date().getFullYear()} Sistemas de Archivos. Todos los derechos reservados.
              </div>
            </div>
          </footer> */}
        </div>
      </body>

    </html >
  );
}
